### ISSUE TITLE
Add support for semi-continuous variables

### ISSUE THREAD

**Issue by jeromepl** [ankane/opt#2]
Hi!

For a project I would need support for semi-continuous variables. I know they are [supported by HiGHS](https://ergo-code.github.io/HiGHS/dev/structures/enums/#HighsVarType) and I have used them [in SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.milp.html)

I would love to contribute this to the project (thanks for the amazing effort to bring all these tools to Ruby by the way!) but was wondering a couple of things first:
- At this point do you recommend using/updating this gem or [or-tools-ruby](https://github.com/ankane/or-tools-ruby) instead? I'd have to do a bit more research to see if OR tools supports semi-continuous variables too.
- Do you have any idea how to implement this in a way that plays well with other solvers? I'm assuming not all solvers support this type of variable, so should I plan to raise exceptions if trying to use this type of variable somewhere it's not supported? If so, where would you recommend doing this check?

**Comment by ankane** [comment]
Hi @jeromepl, thanks for the suggestion and wanting to contribute.

1. I believe ORTools only supports semi-continuous variables with the [original solver](https://developers.google.com/optimization/cp/original_cp_solver) (which I wasn't planning to add to Ruby), so think it'd be better here.
2. For implementation/other solvers, I think we could add `:nlp` and `:minlp` problem types (search the code for `:qp` to see how that's implemented).

**Comment by jeromepl** [comment]
By `:nlp` and `:minlp` you mean adding support for non-linear programming? I think that's out of scope for what I'm trying to achieve. Semi-continuous variables don't make a problem non-linear.

That said, we could still add support for this type of variable through a new problem type; I'm just not sure what we could name it.

Some updates on my side since yesterday:
- I checked and none of the other solvers support semi continuous variables
- There is an easy-ish way to convert semi-continuous variables into a set consisting of: 1 binary variable, 1 continuous variable, and a couple of inequality constraints ([source](http://yetanothermathprogrammingconsultant.blogspot.com/2016/08/semi-continuous-variables.html))

This means I see at least the following ways of implementing this here:
1. Add a new problem type (name TBD). Only `HiGHS` will support this new type and any problem using a `SemiContinuous` variable will automatically be converted to that problem type.
2. Same as option 1 but without the new problem type. Instead, the `Problem#solve` method will take care of raising an exception if the solver is `:highs` and a variable of this type is used.
3. Allow using `SemiContinuous` variables with any solver that supports `:mip` by automatically converting the `SemiContinuous` variable into a set of variables and contraints as explained [here](http://yetanothermathprogrammingconsultant.blogspot.com/2016/08/semi-continuous-variables.html).

What I don't like about option 3 is that we are not taking care of potential optimisations of HiGHS when it comes to semi-continuous variables as they would be converted to binary and continuous variables before being sent to HiGHS. To fix this, we could refactor a lot of the code to make it easier for each solver to customize how they handle each variable type, or adding some sort of conversion pipeline.
However, it does sound like the most flexible option.

Curious to hear your thoughts before I dive deeper into the code!

**Comment by ankane** [comment]
My bad, let’s start with 2, and can do 3 for other MIP solvers later if needed.
