### ISSUE TITLE
SystemStackError: stack level too deep for larger problems

### ISSUE THREAD

**Issue by mjvanderboon** [ankane/opt#6]
Hi,

Thanks for making this great package.

I ran into the error in the title while experimenting with the package using the GLPK solver. The error only seems to occur for problems larger than a certain size. Below is an example which produces the error:

```
    x = []
    size = 10000
    for i in 0..size
      x[i] = Opt::Variable.new(0.., "x#{i}")
    end

    prob = Opt::Problem.new
    prob.minimize(x.reduce(:+))
    prob.solve(solver: :glpk, verbose: true)
```

Reducing the size parameter with a factor 10 to 1000 removes the error and the problem solves. Do you have any background on this error? Are there any workarounds for it?

**Comment by ankane** [comment]
Hi @mjvanderboon, thanks for reporting! Fixed in the commit above.
